hms-dbmi-cellenics/pipeline

- cloudformation-states.yaml
https://biomage.atlassian.net/browse/BIOMAGE-507
N/A
N/A
N/A
A CloudFormation file can deploy a state machine that can call into the Kubernetes cluster.
> Add Cloudformation file for deploying state machine with simple pipeline

- remoter-client/src/wrapper.r
Quick fix to the "Cannot assign name to different value in the given environment. Name already in use" error that didn't allow the rest of the pipeline to run. 
> Small fix for pipeline namespaces

- README.md
- remoter-client/src/init.r
N/A
N/A
N/A
Fixes a broken attempt to provide a way to run the pipeline in Linux.
> Fix host.docker.internal override

- remoter-client/src/wrapper.r
- remoter-server/src/test_fn.r
https://biomage.atlassian.net/browse/BIOMAGE-653
https://ui-martinfosco-ui160-api70-pi.scp-staging.biomage.net/
https://github.com/biomage-ltd/ui/pull/160
https://github.com/biomage-ltd/api/pull/70
> Investigate and implement mechanism to pass large plotData from QC

- remoter-client/src/wrapper.r
- remoter-server/src/computeEmbedding.r
- remoter-server/src/configureEmbedding.r
https://biomage.atlassian.net/browse/BIOMAGE-682?atlOrigin=eyJpIjoiMTBiNGMwY2VkOTEzNDViMGFlOWMzYjAyNDA0ZWI0MzgiLCJwIjoiaiJ9
Before merging, changes related with Multisample support should be added (#13).
> Embedding step

- chart-infra/templates/kube-cleanup-operator-deployment.yaml
https://biomage.atlassian.net/browse/BIOMAGE-731
N/A
N/A
As said in the ticket, a straight up copy-paste from [here](https://github.com/biomage-ltd/worker/blob/master/chart-infra/templates/kube-cleanup-operator-deployment.yaml) in the `worker` repository, with the TTL value being modified to 30 minutes.
Added a deployment to the `pipeline` repository that will delete completed jobs after 30 minutes. This is enough time for AWS to find the job to be complete (the AWS polling rate can be in the extreme once every 10 minutes), but does not leave crap behind.
To deploy to the staging …
> Add cleanup operator to pipeline repository

- remoter-server/src/cellSizeDistribution.r
- remoter-server/src/configureEmbedding.r
There wasn't a ticket for this one, I just thought I'd fix the grey colors on the embedding by sample. It was unnecessary not to repeat the colors used in the embedding by clusters so I removed that bit of code and now the grey color is not being used.
> Fix grey color on samples embedding

- qc-runner/src/dataIntegration.r
- qc-runner/src/init.r
In the process to migrate code from data-ingest to pipeline, gene dispersion was not calculated correctly.
Note, in order for this to work, the Seurat object needs `scdata@misc[["gene_annotations"]]` to be present, which should normally be added by data-ingest, but has been found to be absent for some data.
This code should fix this.
https://ui-oliver-w99p35.scp-staging.biomage.net/experiments/e52b39624588791a7889e39c617f669e/data-exploration
Is all relevant documentation …
> adding FindVariableFeatures code to calc gene dispersion

- qc-runner/src/dataIntegration.r
At the moment we are not handling the case in which the user overly-filters the dataset, leading to errors in those cases. This also applies to the case when all cells of one sample have been filtered, or even when all the cells of all samples - 1 have been filtered leading us to have a unisample from a seemingly multisample object. See this discussion for details:
https://this-is-biomage.slack.com/archives/C01CP46TJ0Z/p1619106701119000
-Decide how to deal with overfiltered (empty or almost-empty) datasets
-Implement the required changes if on the pipeline, or create a ticket and coordinate with engineering the implementation from the UI.
After exploring and testing this issue I came to the following conclusion:
- It is hard to set fixed threshold to prevent users from over filtering …
> Dealing with too few cells in pipeline

- local-runner/src/app.js
- qc-runner/src/init.r
N/A
Issue in the local development environment
In our latest attempt to make life simpler for linux user, we broke the environment for MacOS users, overriding with an empty string `host.docker.internal`
* Prevent the `host.docker.internal` override
* Wait for clouformation operations to complete before the next step
> Lost host address

- qc-runner/src/doubletScores.r
We can have NA `doublet_scores` as they are only calculated on non-empty droplets (`ed.out$FDR < 0.001`). This commit handles NA's:
> handle NA doublet scores

- local-runner/cf-local-container-launcher.yaml
Minor changes.
* echo the docker command launched by lambda functions in local development
* set lambda timeout as an integer rather than as a string https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-timeout
> Display the command used to launch docker from lambda

- pipeline-runner/src/data-ingest/4_Prepare_experiment.r
Also fixed in data-ingest: https://github.com/biomage-ltd/data-ingest/pull/34
The function `add_custom_config_per_sample` wasn't subsetting the dataset. This created a bug where the entire object was being used to calculate default cellSizeDistribution, numGenesVsNumUmis and doubletScore thresholds. For example all the doubletScore thresholds end up the same:
This is the same value as if I calculate the threshold with the full seurat object:
Whereas e.g. for an actual sample subset we get something different for each sample:
> fix per sample custom config

- pipeline-runner/src/cellSizeDistribution.r
- pipeline-runner/src/data-ingest/0-download_gem2s.r
- pipeline-runner/src/data-ingest/1_Preproc.r
- pipeline-runner/src/data-ingest/2-1_Compute-metrics_emptyDrops.r
- pipeline-runner/src/data-ingest/2-2_Compute-metrics_doublets.r
- pipeline-runner/src/data-ingest/3_Seurat.r
- pipeline-runner/src/data-ingest/4_Prepare_experiment.r
- pipeline-runner/src/data-ingest/5_Upload-to-aws.r
- pipeline-runner/src/handle_data.r
- pipeline-runner/src/init.r
- pipeline-runner/src/mitochondrialContent.r
https://biomage.atlassian.net/browse/BIOMAGE-1009
https://ui-martinfosco-ui289-api136-p.scp-staging.biomage.net/
https://github.com/biomage-ltd/ui/pull/289
https://github.com/biomage-ltd/api/pull/136
> [BIOMAGE-1009] Fix error sns messages

- pipeline-runner/src/data-ingest/2-2_Compute-metrics_doublets.r
scDblFinder is the current bottleneck in GEM2S. This should be faster and also prevent errors from asking for doublet scores when there are lots of empty droplets in the matrix.
Staging link:
https://ui-oliver-p78.scp-staging.biomage.net/
https://ui-mvpdev.scp-staging.biomage.net/
> port doublet score code from data-ingest

- .github/workflows/draft-new-release.yaml
- .github/workflows/prevent-pr-to-master.yaml
- .github/workflows/publish-new-release.yaml
Create new github actions for release style.
Now we'll have a `draft release` button which will create a new release branch called `release/version` & PR.
Once that branch is tested, merging it will trigger the new release, creating a tag, merging into master and creating PR to merge into develop.
The new flow also supports creating branches called hotfix/* to merge into master directly.
> new flow for releases

- .github/workflows/ci.yaml
As PRs to master were not allowed, the new release PRs are not being built. Allow them to be built only for branches names `release/*` or `hotfix/*`.
> added deployment for release/hotfixes PRs to master

- Makefile
On Linux the `HOST_IP` variable needs to be set manually. Previously this was done with `hostname -I`. This was unreliable as a) not all versions of hostname have this option and b) the output order [is not guaranteed](https://stackoverflow.com/questions/13322485/how-to-get-the-primary-ip-address-of-the-local-machine-on-linux-and-os-x#comment40729437_25851186). Instead, we get the address of Docker's bridge network directly using `docker config`.
[Credit for the new command goes here.](https://stackoverflow.com/a/55224655/7799676)
Changed how `HOST_IP` is set on Linux in `Makefile`
To …
> Fix determination of HOST_IP on Linux

- pipeline-runner/src/configureEmbedding.r
- pipeline-runner/src/data-ingest/4_Prepare_experiment.r
https://biomage.atlassian.net/browse/BIOMAGE-973?atlOrigin=eyJpIjoiMzVjMDc3OTNhMTM3NDlmOWI5MmEyNjQ3MTU1MTQwNjkiLCJwIjoiaiJ9
https://ui-juanlu-pipeline88.scp-staging.biomage.net/
Neither auto and enabled are relevant for dataIntegration and configureEmbedding. Both are required for single cell analysis. In case of excluding the use of dataIntegration, the user must select No integration in the drop-down list. 
I have requested the correction of an engineer to be able to test in greater depth the api and ui without these two entries. 
To deploy to the staging environment, follow the …
> Rm auto and enabled

- pipeline-runner/src/cellSizeDistribution.r
- pipeline-runner/src/classifier.r
- pipeline-runner/src/data-ingest/test_object.r
- pipeline-runner/src/doubletScores.r
- pipeline-runner/src/mitochondrialContent.r
- pipeline-runner/src/numGenesVsNumUmis.r
[BIOMAGE-967](https://biomage.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=BIOMAGE&modal=detail&selectedIssue=BIOMAGE-967)
This also fixes a bug for the knee plot: it was not previously calculating the knee per sample as it was using `orig.ident` for grouping
> switch from orig.ident to samples

- README.md
- local-runner/package.json
I updated my docker and it doesn't seem to like unset host part on volume anymore:
To resolve I've hardcoded the `DEBUG_PATH=$(pwd)/debug`. In addition to fixing this issue it also simplifies debug specification and always exposes a host path where it's possible to save something that will be available outside of the container. 
This provides a nice use patern that I find myself using: instead of specifying a DEBUG_STEP, you can just save something in `/debug`. I have used this for gem2s debugging where the DEBUG_STEP is not set up.
> hardcode DEBUG_PATH

- pipeline-runner/Dockerfile
Docker build is failing due to changes in `seurat-wrappers` which now require `R.utils` to be installed.
https://github.com/biomage-ltd/pipeline/runs/2821632997?check_suite_focus=true#step:9:4390
> added r.utils dependency install which is required by seurat-wrappers

- Makefile
- Adds `build` as dependency of `run`
- Adds `run-only` target
> Update run targets to match worker

- pipeline-runner/R/gem2s-6-prepare_experiment.R
https://ui-martinfosco-api172-pipelin.scp-staging.biomage.net/
https://github.com/biomage-ltd/api/pull/172
The api was performing the changes added in the PR, there seemed to be some inconsistent behavior on the api in staging for this so I decided to move it over to the pipeline now in order to avoid potential bugs (which was already the plan in the long run).
> Move defaultFilterSettings and missing per sample config additions to the pipeline

- pipeline-runner/R/gem2s-4-score_doublets.R
https://biomage.atlassian.net/browse/BIOMAGE-1310
> more restrictive filtering

- pipeline-runner/R/handle_data.R
- pipeline-runner/codecov.yaml
- pipeline-runner/codecov.yml
https://this-is-biomage.slack.com/archives/C0250TDU1PF/p1628765252019300
In API repo
API - https://github.com/biomage-ltd/api/pull/201
- Changed upload count matrix method to use multipart upload
> Upload count matrix with multipart upload

- .github/workflows/ci.yaml
> Fix `glob:` doubling causing wrong images to be staged for environments

- pipeline-runner/init.R
> fixed wrong api app name in config

- .github/workflows/ci.yaml
`access-token` in the the branch protection CI step we are using is changed to `access_token`, causing deployment to fail.
Breaking changes : benjefferies/branch-protection-bot@2b60c2b
> Fix ci access token

- pipeline-runner/init.R
https://biomage.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=BIOMAGE&modal=detail&selectedIssue=BIOMAGE-1427
N/A
https://github.com/biomage-ltd/iac/pull/176
N/A
After the fix in https://github.com/biomage-ltd/iac/pull/176, this ensures that service names do not have to be specifically adjusted for production.
> [BIOMAGE-1427] Fix the config difference for staging and production services

- pipeline-runner/init.R
`host.docker.internal` doesn't exist for linux. This uses `HOST_IP` for linux as set in the makefile.
Staging link
https://ui-olivergibson-pipeline170.scp-staging.biomage.net/
> use HOST_IP for api url

- .github/workflows/ci.yaml
- pipeline-runner/DESCRIPTION
- pipeline-runner/R/qc-6-integrate_scdata.R
- pipeline-runner/renv.lock
https://biomage.atlassian.net/browse/BIOMAGE-1392
https://biomage.atlassian.net/browse/BIOMAGE-1556
https://ui-alex-ui569-pipe190.scp-staging.biomage.net/
https://github.com/biomage-ltd/ui/pull/569
**Test data**: https://drive.google.com/drive/u/1/folders/1ioY1k6Or_461NtbH60npiCJfy8DPgKs6
**NOTE**: hangs in productions, not in staging
Cause of issue: https://github.com/aryoda/tryCatchLog/issues/68
Is all relevant documentation updated to reflect the proposed changes in this …
> Fix trycatch hanging

- .github/workflows/ci.yaml
- .github/workflows/pr_validate.yaml
- Make PR update step in CI case insensitive
- Auto uncheck integration test box
N/A
N/A
https://github.com/hms-dbmi-cellenics/api/pull/291
master
> Make PR update step in CI case insensitive

- .github/workflows/pr_validate.yaml
- pipeline-runner/Dockerfile
- pipeline-runner/setup/check_package_licenses.R
- pipeline-runner/setup/create_ghost_packages.R
- removes packages with potentially conflicting licenses
- checks all dependencies for potentially conflicting licenses
N/A
N/A
https://github.com/hms-dbmi-cellenics/worker/pull/295
master
> Init ghost packages

- local-runner/src/app.js
Due to recent modifications to `app.js` setting up the `AWS_DEFAULT_REGION` env variable was required. The error was very obscure, because when creating the lambda function is uses a default with region: `process.env.AWS_DEFAULT_REGION || 'eu-west-1'`. However, when adding the variable to the template it does not (which is the latest addition) causing the pipeline to fail once it started.
I modified the code to set the default for the whole file instead of just for one of the cases.
N/A
N/A
master
Integration tests have to pass before the …
> Using a whole-file default value for region

- pipeline-runner/R/gem2s-7-upload_to_aws.R
- pipeline-runner/tests/testthat/test-gem2s-7-upload_to_aws.R
When sample cellsets contain regex characters, subsetting an experiment fails. This is caused by the pattern matching used to extract the sample metadata track names from the cellsets object. 
For example, if an experiment contains a track `metadata_var` with values `value_1+`, and `value_1-` the experiment will have a cell class `metadata_var` with two cellsets (note the `key` and `name`):
```
{
key: "metadata_var-value_1+",
name: "value_1+",
type: "metadataCategorical",
...
},
{
key: "metadata_var-value_1-",
name:"value_1-",
type: "metadataCategorical",
...
}
```
To extract the variable name, we currently pattern match the name in the key using `gsub`. But the `+` is interpreted as a regex character, which makes the replacement incorrect (but does not fail).
The solution is to escape …
> fix(subset-pipeline): metadata with regex chars

- pipeline-runner/R/qc-4-filter_gene_umi_outlier.R
- pipeline-runner/tests/testthat/test-qc-4-filter_gene_umi_outlier.R
The UI/API do not change the value of the p.level parameter sent in the config, but when auto is disabled, it adds a new `predictionInterval` parameter, which was not used at all in the pipeline, always defaulting to the auto estimated `p.level` value. Therefore changes to the filter did not produce the intended filtering.
This PR takes the `predictionInterval` parameter value and actually uses it to define the `p.level` parameter used by the `predict` function.
N/A
N/A
master
Integration tests have to pass before the PR can be merged. …
> HOTFIX: genes v umi filter not using user-defined parameters

- pipeline-runner/R/seurat-3-upload_seurat_to_aws.R
- pipeline-runner/tests/testthat/test-seurat-3-upload_seurat_to_aws.R
Excludes columns that start with `scDblFinder` from uploaded Seurat objects
https://github.com/hms-dbmi-cellenics/issues/issues/107
N/A
master
> exclude scDblFinder columns from Seurat uploads

- pipeline-runner/R/qc-6-integrate_scdata-seuratv4.R
- pipeline-runner/R/qc-6-subsample-geosketch.R
- pipeline-runner/tests/testthat/test-qc-6-integrate_scdata-seuratv4.R
Seurat integration is broken when used in combination with SCTransform and geometric sketching. This is because after SCTransform is performed, we should not calculate variable features on the "RNA" assay. To address this issue, the fix involves using SelectIntegrationFeatures to obtain variable features form the "SCT" assay. See here: https://github.com/satijalab/seurat/issues/5761.
This PR implements the necessary changes.
N/A
N/A
master
**will …
> Fix Seurat v4 integration issue with SCTransform and geosketch

- pipeline-runner/R/seurat-3-upload_seurat_to_aws.R
Seurat upload fails if there are NAs in the metadata. This PR fixes this issue making sure that columns with NA values are not considered as candidates for cluster column. Metadata columns with NA values are still kept and visible as metadata values in the platform.
Staging: https://ui-sara-pipeline15.scp-staging.biomage.net/
N/A
N/A
master
> Fix Seurat upload bug

- pipeline-runner/R/seurat-3-upload_seurat_to_aws.R
- pipeline-runner/tests/testthat/test-seurat-3-upload_seurat_to_aws.R
`make_vals_numeric` would produce all NAs for columns formatted as dates (e.g. classes `Date` or `POSIXct` or `POSIXt`) which results in an error from `test_groups_equal` (used by `find_cluster_columns`).  
This fixes that issue by coercing values to be character initially.
N/A
N/A
master
> fix dates for make_vals_numeric

- pipeline-runner/R/seurat-3-upload_seurat_to_aws.R
- pipeline-runner/tests/testthat/test-seurat-3-upload_seurat_to_aws.R
If `active.ident` was factor and there is an identical `character` column then `rename_active_ident` didn't identify them as identical. This fixes that
N/A
N/A
master
> make rename_active_ident work with factor+character

- pipeline-runner/Dockerfile
- pipeline-runner/renv.lock
- pipeline-runner/renv/activate.R
- pipeline-runner/renv/settings.json
This change modifies the Dockerfile to install the latest version of `renv` from GitHub instead of using a fixed version.
This was done because the pipeline build was failing locally.
N/A
N/A
master
> Use latest renv version
