local-runner/cf-local-container-launcher.yaml

https://biomage.atlassian.net/browse/BIOMAGE-506
N.A.
https://github.com/biomage-ltd/api/pull/58
- `remoter-server` fails to launch because it's passed an empty parameter `""`. This merge request removes that while still passing in the correct JSON format to `remoter-client`.

fix passing task to remoter-client

---

remoter-client/src/init.r
remoter-client/src/wrapper.r
remoter-server/src/cellSizeDistribution.r

https://biomage.atlassian.net/browse/BIOMAGE-640

Cell size filter

---

remoter-client/src/init.r
remoter-client/src/wrapper.r
remoter-server/src/cellSizeDistribution.r
remoter-server/src/classifier.r
remoter-server/src/doubletScores.r
remoter-server/src/mitochondrialContent.r
remoter-server/src/numGenesVsNumUmis.r

https://biomage.atlassian.net/browse/BIOMAGE-646
https://biomage.atlassian.net/browse/BIOMAGE-645
https://biomage.atlassian.net/browse/BIOMAGE-643
https://biomage.atlassian.net/browse/BIOMAGE-642
Staging would be broken at this stage because there are multiple things to fix in the UI and API.
Refer to this slack post.
- [ X] Tested locally with Inframock
- [X ] Photo of a cute animal attached to …

Pipeline filters

---

remoter-server/src/cellSizeDistribution.r

https://biomage.atlassian.net/browse/BIOMAGE-673

fix knee plot in QC pipeline

---

remoter-client/src/init.r
remoter-client/src/wrapper.r
remoter-server/src/test_fn.r

https://biomage.atlassian.net/browse/BIOMAGE-521
TBD
TBD
N/A
A simple fix which allows us to select one of the samples from the `processingConfig` before sending it to the bioinformatics scripts. The data you get here is different from the normal processing config, the to-be-posted PR on the API will shed more light on this.

Cellscope to handle multisample data sets

---

remoter-server/src/cellSizeDistribution.r
remoter-server/src/doubletScores.r
remoter-server/src/mitochondrialContent.r
remoter-server/src/numGenesVsNumUmis.r
remoter-server/src/utils.r

https://biomage.atlassian.net/browse/BIOMAGE-692
- [X ] Photo of a cute animal attached to this PR

Multisampe per sample subsetting

---

remoter-server/src/configureEmbedding.r

Fix embedding

---

remoter-server/Dockerfile
remoter-server/src/dataIntegration.r

[BIOMAGE-720](https://biomage.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=BIOMAGE&modal=detail&selectedIssue=BIOMAGE-720)
https://ui-alex-pipeline24.scp-staging.biomage.net/

Fix integration

---

remoter-server/src/classifier.r

https://biomage.atlassian.net/browse/BIOMAGE-680

Fix classify filter

---

qc-runner/src/dataIntegration.r

Enabled missing from data integration because it was removed from dynamo.

Fix enabled missing

---

qc-runner/src/dataIntegration.r

Embedding and cluster plots by sample not showing up. 

Potential fix for missing plots

---

qc-runner/src/init.r

https://biomage.atlassian.net/browse/BIOMAGE-754
in UI repo : https://github.com/biomage-ltd/ui/pull/192
UI : https://github.com/biomage-ltd/ui/pull/192
Worker : https://github.com/biomage-ltd/worker/pull/94
Pipeline : https://github.com/biomage-ltd/pipeline/pull/31
API : https://github.com/biomage-ltd/api/pull/86
IAC : https://github.com/biomage-ltd/iac/pull/53
- Add new environment variable `uploadCountMatrix` which tells the step to upload the count matrix or not
- Add function to upload count matrix to S3 bucket
To deploy to the staging environment, follow the instructions here: …

Upload processed count matrix

---

qc-runner/src/dataIntegration.r

[BIOMAGE-780](https://biomage.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=BIOMAGE&modal=detail&selectedIssue=BIOMAGE-780)
https://ui-alex-pipeline37.scp-staging.biomage.net/experiments/55b015513f2880111336326eed1801a5/data-processing
This is just a sanity check that indeed dataIntegration is being run with a unisample dataset. The print happened in staging so we are good to go. I'll crossreference the PR to reflect the same changes in data-ingest.
Is all …

test that unisample runs data integration steps

---

Makefile
README.md
docker-compose.linux-dev.yaml
qc-runner/src/init.r

Added Makefile for convenience

added makefile

---

.github/pull_request_template

Added small reminder to PR template to update local data when testing with inframock.

updated PR template to include reminder to update local data

---

.github/workflows/ci-develop.yaml

Test to ensure that we can create staging deployments using GitFlow workflows.

Add new CI pipeline for merging things into develop

---

qc-runner/src/cellSizeDistribution.r
qc-runner/src/dataIntegration.r

https://biomage.atlassian.net/browse/BIOMAGE-871?atlOrigin=eyJpIjoiYjcxMWU5OTViZmI5NDYzZWE1YzhhNDQ0MDJhZGVhN2MiLCJwIjoiaiJ9
https://ui-juanlu-pipeline47.scp-staging.biomage.net/experiments/352cb8d159d650c13bc4acd5f7442993/data-processing
When ingesting the experiment of user 6 (352cb8d159d650c13bc4acd5f7442993), two errors occurred due to the fact that the number of cells in some samples is very small (less than 100).
- cellSizeDistribution (due to CalculateBarcodeInflections cannot handle dataset with less that 100 cells. 100 is a hardcode value of threshold.low)
- dataIntegration (seurat v4 integration method fails with samples with less than 100 cells)
To set up easy local testing with inframock, …

Fix cellSizeDistribution and dataIntegration for small dataset

---

Makefile
local-runner/cf-local-container-launcher.yaml
local-runner/src/app.js

Makefile needed some [black magic](https://lists.freebsd.org/pipermail/freebsd-questions/2012-September/244810.html) to get `awk` command to work

fix makefile for linux

---

README.md
qc-runner/src/init.r

Changes:
- saves objects using parameter names instead of argument names (makes more sense as can directly use to step through function)
- reflect Makefile usage for debug in README

update debug stuff

---

qc-runner/src/dataIntegration.r

https://biomage.atlassian.net/browse/BIOMAGE-876
https://ui-oliver-p59.scp-staging.biomage.net/experiments/oliver-p59-e52b39624588791a7889e39c617f669e/data-processing
- [X ] Photo of a cute animal attached to this PR

Added no integration

---

qc-runner/Dockerfile
qc-runner/src/configureEmbedding.r
qc-runner/src/dataIntegration.r

https://biomage.atlassian.net/browse/BIOMAGE-900?atlOrigin=eyJpIjoiMWE2ZDRjZGZmMmU5NGYyOWE3YTQyODcxYjZkNWUwNzIiLCJwIjoiaiJ9
https://ui-juanlu-ui246-api107-worker.scp-staging.biomage.net/experiments/juanlu-ui246-api107-worker-e52b39624588791a7889e39c617f669e/data-processing
https://github.com/biomage-ltd/api/pull/107
https://github.com/biomage-ltd/ui/pull/246
In a Seurat object we have the slot `reductions` and `assays`. Integrated method `SeuratV4`use set the `reduction` to pca and the `assay` to integrated, whereas FastMNN set the `reduction` to mnn and the `assay` to RNA. By defatult, there is a parameter inside the seurat object called `active.assay`, which allow us track which assay we need to use, however, there is no information about which reduction use. To solve it, we have …

Add FastMNN step 6-7

---

pipeline-runner/src/data-ingest/2-1_Compute-metrics_emptyDrops.r
pipeline-runner/src/data-ingest/2-2_Compute-metrics_doublets.r
pipeline-runner/src/data-ingest/3_Seurat.r
pipeline-runner/src/data-ingest/4_Prepare_experiment.r
pipeline-runner/src/data-ingest/5_Upload-to-aws.r

Various bugs in gem2s.
- [X ] Tested locally with Inframock (with latest production data downloaded with biomage experiment pull)

Dependency issues and cellsets

---

pipeline-runner/src/data-ingest/0-download_gem2s.r
pipeline-runner/src/data-ingest/1_Preproc.r
pipeline-runner/src/data-ingest/2-1_Compute-metrics_emptyDrops.r
pipeline-runner/src/data-ingest/2-2_Compute-metrics_doublets.r
pipeline-runner/src/data-ingest/3_Seurat.r
pipeline-runner/src/data-ingest/4_Prepare_experiment.r
pipeline-runner/src/data-ingest/5_Upload-to-aws.r
pipeline-runner/src/handle_data.r

https://biomage.atlassian.net/browse/BIOMAGE-947
https://biomage.atlassian.net/browse/BIOMAGE-984
https://ui-martinfosco-ui274-api127-w.scp-staging.biomage.net/
https://github.com/biomage-ltd/ui/pull/274
https://github.com/biomage-ltd/api/pull/127
Following the way we handle tasks completion in the qc pipeline, in gem2s the api needs to receive status updates when steps are finished. This way we can cause the api to send updates to the ui on what step we are at, this PR is my attempt to do this, it was working in localhost but there might be a better way to do it so feel free to comment/change the code as necessary.
To set up easy local testing with inframock, follow the instructions here: …

Handle gem2s response

---

pipeline-runner/src/data-ingest/4_Prepare_experiment.r
pipeline-runner/src/data-ingest/5_Upload-to-aws.r

https://this-is-biomage.slack.com/archives/C015CHSUDRU/p1622108281138400?thread_ts=1622105945.135000&cid=C015CHSUDRU
N.A.
#69 
- Fix invalid reference in the function `add_custom_config_per_sample`
Kudos to @xverges for the fix!

Fix seurat obj not found

---

pipeline-runner/src/data-ingest/0-download_gem2s.r
pipeline-runner/src/data-ingest/1_Preproc.r
pipeline-runner/src/data-ingest/2-1_Compute-metrics_emptyDrops.r
pipeline-runner/src/data-ingest/2-2_Compute-metrics_doublets.r
pipeline-runner/src/data-ingest/3_Seurat.r
pipeline-runner/src/data-ingest/4_Prepare_experiment.r
pipeline-runner/src/data-ingest/5_Upload-to-aws.r
pipeline-runner/src/handle_data.r
pipeline-runner/src/init.r

https://ui-martinfosco-uidevelop-api.scp-staging.biomage.net/
https://github.com/biomage-ltd/api/pull/129
Changes that came up from the code review for ticket https://biomage.atlassian.net/browse/BIOMAGE-947 with marcell, forgot to push them.

Handle gem2s response refactoring

---

pipeline-runner/src/data-ingest/0-download_gem2s.r
pipeline-runner/src/data-ingest/4_Prepare_experiment.r
pipeline-runner/src/data-ingest/5_Upload-to-aws.r

https://biomage.atlassian.net/browse/BIOMAGE-1016
https://ui-oliver-ui277p72.scp-staging.biomage.net/experiments/716d51c2272054c432a93bd543a1eec9/plots-and-tables

[BIOMAGE-1016] Sample uuids fix

---

pipeline-runner/src/data-ingest/4_Prepare_experiment.r
pipeline-runner/src/data-ingest/5_Upload-to-aws.r

https://ui-juanlu-pipeline75.scp-staging.biomage.net
There was a bug during the GEM2S migration were the `FastMNN` slot was not included. 

Fix fast mnn

---

pipeline-runner/src/data-ingest/0-download_gem2s.r
pipeline-runner/src/data-ingest/4_Prepare_experiment.r
pipeline-runner/src/data-ingest/5_Upload-to-aws.r

https://biomage.atlassian.net/browse/BIOMAGE-1040
In related API PR
API : https://github.com/biomage-ltd/api/pull/135
Pipeline : https://github.com/biomage-ltd/pipeline/pull/74
- Fix GEM2S data structures as expected by the system

[BIOMAGE-1040] - Fix metadata structures

---

pipeline-runner/src/data-ingest/4_Prepare_experiment.r

https://biomage.atlassian.net/browse/BIOMAGE-920?atlOrigin=eyJpIjoiYTgyZjk2Y2QyZjliNDYwN2FmMWUwZmRkYzkzODI0YTUiLCJwIjoiaiJ9
https://ui-juanlu-pipeline77.scp-staging.biomage.net/

Add experimentID and ingestionDate

---

pipeline-runner/src/mitochondrialContent.r

https://this-is-biomage.slack.com/archives/C01CP46TJ0Z/p1622712306012600
https://ui-agi-pipeline79.scp-staging.biomage.net/
N.A.
- Plot data was previously overwritten because they're using the same index. Index changed.

fix mtcontent plotdata error

---

pipeline-runner/src/data-ingest/4_Prepare_experiment.r

https://biomage.atlassian.net/browse/BIOMAGE-1057

Fix doublet settings

---

local-runner/cf-local-container-launcher.yaml
local-runner/src/app.js

`-t` flag for docker run to fix the output and prevent annoying bells. 
https://github.com/apocas/dockerode#streams-goodness
The changes to `app.js` are only to cleanup the code.

Add tty flag to fix local output

---

pipeline-runner/src/data-ingest/5_Upload-to-aws.r
pipeline-runner/src/handle_data.r

https://biomage.atlassian.net/browse/BIOMAGE-1083?atlOrigin=eyJpIjoiMWI1NmZlNzU1NWZiNGM3MDk0NDU4N2E4N2ZkOWJjOTEiLCJwIjoiaiJ9
https://ui-juanlu-pipeline94.scp-staging.biomage.net/

Move to multipart upload

---

pipeline-runner/src/data-ingest/0-download_gem2s.r

https://biomage.atlassian.net/browse/BIOMAGE-1044
https://ui-martinfosco-ui319-api147-p.scp-staging.biomage.net/
https://github.com/biomage-ltd/ui/pull/319
https://github.com/biomage-ltd/api/pull/147

[BIOMAGE-1044] Detect for changes in a project and allow data reingest

---

pipeline-runner/src/data-ingest/4_Prepare_experiment.r

https://this-is-biomage.slack.com/archives/C015CHSUDRU/p1623427177070300
https://ui-agi-pipeline97.scp-staging.biomage.net/
N.A.
- Remove LOC that sets `auto` and `enabled` to NULL

Re-enable per sample config

---

pipeline-runner/src/numGenesVsNumUmis.r

https://biomage.atlassian.net/browse/BIOMAGE-1117?atlOrigin=eyJpIjoiMDc5NjBlYjQ0OGMyNDcyYTlhNzBmMGQ2N2NmYjgyNmIiLCJwIjoiaiJ9
https://ui-juanlu-pipeline102.scp-staging.biomage.net/

Fix p.level

---

pipeline-runner/src/init.r
pipeline-runner/src/mitochondrialContent.r

https://biomage.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=BIOMAGE&modal=detail&selectedIssue=BIOMAGE-916
https://ui-stefan-ui338.scp-staging.biomage.net/
UI - https://github.com/biomage-ltd/ui/pull/338
API - https://github.com/biomage-ltd/api/pull/161
Pipeline - https://github.com/biomage-ltd/pipeline/pull/101

Retrieve errors thrown by pipeline from the state machine and display on UI

---

pipeline-runner/R/gem2s-6-prepare_experiment.R

https://this-is-biomage.slack.com/archives/C0250TDU1PF/p1624894452010100

Fix defaults

---

pipeline-runner/R/gem2s-1-download_cellranger.R
pipeline-runner/R/gem2s-2-load_cellranger.R
pipeline-runner/R/gem2s-3-run_emptydrops.R
pipeline-runner/R/gem2s-4-score_doublets.R
pipeline-runner/R/gem2s-5-create_seurat.R
pipeline-runner/R/gem2s-6-prepare_experiment.R
pipeline-runner/R/gem2s-7-upload_to_aws.R
pipeline-runner/R/gem2s-helpers.R
pipeline-runner/R/qc-1-filter_emptydrops.R
pipeline-runner/R/qc-2-filter_low_cellsize.R
pipeline-runner/R/qc-3-filter_high_mito.R
pipeline-runner/R/qc-4-filter_gene_umi_outlier.R
pipeline-runner/R/qc-5-filter_doublets.R
pipeline-runner/R/qc-6-integrate_scdata.R
pipeline-runner/R/qc-7-embed_and_cluster.R

https://biomage.atlassian.net/browse/BIOMAGE-968

Clean pipeline code

---

pipeline-runner/src/data-ingest/5_Upload-to-aws.r

Fix bool name

---

pipeline-runner/R/qc-7-embed_and_cluster.R

https://biomage.atlassian.net/browse/BIOMAGE-971
https://ui-api168p107.scp-staging.biomage.net/

Removed embedding

---

pipeline-runner/R/gem2s-7-upload_to_aws.R

https://biomage.atlassian.net/browse/BIOMAGE-957
https://github.com/biomage-ltd/iac/pull/151

[BIOMAGE-957] Rename 'Scratchpad' to 'Custom cell sets'

---

pipeline-runner/R/gem2s-6-prepare_experiment.R

Fixed no unique rownames

---

.github/workflows/ci.yaml

kubernetes env was not pointing to production

---

pipeline-runner/init.R

I accidentially deleted this in init-trycatchlog :(

fix deleted upload

---

.github/pull_request_template

https://biomage.atlassian.net/browse/BIOMAGE-1342
https://github.com/biomage-ltd/ui/pull/495
https://github.com/biomage-ltd/api/pull/221
https://github.com/biomage-ltd/pipeline/pull/149
https://github.com/biomage-ltd/worker/pull/193

Add integration check to template

---

pipeline-runner/R/gem2s-2-load_cellranger_files.R

Fix repeated rownames

---

pipeline-runner/R/gem2s-6-construct_qc_config.R
pipeline-runner/R/qc-2-filter_low_cellsize.R
pipeline-runner/tests/testthat/test-gem2s-6-construct_qc_config.R

https://ui-olivergibson-pipeline152.scp-staging.biomage.net/

Fix auto low cell size

---

pipeline-runner/R/qc-7-embed_and_cluster.R

Restore double quotes to luvain updates syntax

---

codecov.yaml

https://biomage.atlassian.net/browse/BIOMAGE-1439

[BIOMAGE-1439] Don't allow new commits to decrease coverage

---

pipeline-runner/R/gem2s-2-load_cellranger_files.R
pipeline-runner/R/gem2s-5-create_seurat.R
pipeline-runner/tests/testthat/test-gem2s-2-load_cellranger.R
pipeline-runner/tests/testthat/test-gem2s-5-create_seurat.R

https://biomage.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=BIOMAGE&modal=detail&selectedIssue=BIOMAGE-1300

Test load create

---

.github/workflows/ci.yaml
pipeline-runner/R/gem2s-2-load_cellranger_files.R

https://biomage.atlassian.net/browse/BIOMAGE-1448
https://ui-oliver-p166.scp-staging.biomage.net/
- [X ] Photo of a cute animal attached to this PR

fix extra counts slots

---

pipeline-runner/R/gem2s-5-create_seurat.R

https://ui-olivergibson-pipeline167.scp-staging.biomage.net/

[BIOMAGE-1458] fix metadata

---

pipeline-runner/R/gem2s-helpers.R
pipeline-runner/init.R
pipeline-runner/tests/testthat/test-gem2s-helpers.R

https://ui-olivergibson-p169.scp-staging.biomage.net/

Check metadata

---

pipeline-runner/R/gem2s-7-upload_to_aws.R
pipeline-runner/tests/testthat/_snaps/gem2s-7-upload_to_aws.md
pipeline-runner/tests/testthat/test-gem2s-7-upload_to_aws.R

https://biomage.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=BIOMAGE&modal=detail&selectedIssue=BIOMAGE-1301
https://ui-oliver-pipeline171.scp-staging.biomage.net/

test get_cell_sets and fix failures

---

pipeline-runner/R/qc-4-filter_gene_umi_outlier.R
pipeline-runner/tests/testthat/test-qc-4-filter_gene_umi_outlier.R

https://biomage.atlassian.net/browse/BIOMAGE-1490

fix number of genes

---

pipeline-runner/R/gem2s-5-create_seurat.R
pipeline-runner/tests/testthat/test-gem2s-5-create_seurat.R

https://biomage.atlassian.net/browse/BIOMAGE-1575

change mitochondrial content regex

---

pipeline-runner/R/gem2s-6-construct_qc_config.R
pipeline-runner/R/qc-6-integrate_scdata.R
pipeline-runner/tests/testthat/test-qc-6-integrate_scdata.R

https://biomage.atlassian.net/browse/BIOMAGE-1387
https://ui-german-api268-pipeline193.scp-staging.biomage.net/
https://github.com/biomage-ltd/api/pull/268

estimate number of PCs before embedding

---

pipeline-runner/R/gem2s-2-load_cellranger_files.R

https://ui-olivergibson-p194.scp-staging.biomage.net/

Fix invalid number of columns

---

.flux.yaml
.github/pull_request_template
.github/workflows/ci.yaml
README.md
pipeline-runner/README.md

https://biomage.atlassian.net/jira/software/c/projects/BIOMAGE/boards/1?modal=detail&selectedIssue=BIOMAGE-1640

[BIOMAGE-1640] Change biomage-ltd to hms-dbmi-cellenics

---

.github/workflows/ci.yaml

https://biomage.atlassian.net/browse/BIOMAGE-1652
https://docs.google.com/document/d/1yg-IEUSgveXknVRuj0yz0z36YrSZQSfDvjX8GwxhHxI - Point 16
To set up easy local testing with inframock, follow the instructions here: https://github.com/hms-dbmi-cellenics/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/hms-dbmi-cellenics/biomage-utils

[BIOMAGE-1652] - Change CI to use variables

---

pipeline-runner/R/gem2s-6-construct_qc_config.R

https://biomage.atlassian.net/browse/BIOMAGE-1610
N/A
https://github.com/hms-dbmi-cellenics/ui/pull/623
master

[BIOMAGE-1610] Change bin step default in 2 plots in Data Processing 

---

README.md

remove Biomage and Cellscope references

---

pipeline-runner/R/handle_data.R

Add object tagging to plot data objects
https://biomage.atlassian.net/browse/BIOMAGE-1735
https://ui-agi-pipeline207.scp-staging.biomage.net/
N/A
master

[BIOMAGE-1735] - Add object tagging  to plot data objects

---

pipeline-runner/R/gem2s-6-construct_qc_config.R
pipeline-runner/R/qc-3-filter_high_mito.R
pipeline-runner/tests/testthat/_snaps/gem2s-6-prepare_experiment.md
pipeline-runner/tests/testthat/_snaps/gem2s-7-upload_to_aws.md
pipeline-runner/tests/testthat/test-gem2s-6-construct_qc_config.R
pipeline-runner/tests/testthat/test-qc-3-filter_high_mito.R

uses outlier based adaptive threshold for default mitochondrial percentage filter
https://biomage.atlassian.net/browse/BIOMAGE-1654
https://ui-alex-ui634-pipeline206.scp-staging.biomage.net/
https://github.com/hms-dbmi-cellenics/ui/pull/634
master

[BIOMAGE-1654] - Adaptive mito

---

.github/workflows/ci.yaml
pipeline-runner/init.R

init sessionInfo

---

pipeline-runner/DESCRIPTION
pipeline-runner/R/qc-7-embed_and_cluster.R
pipeline-runner/R/qc-helpers.R
pipeline-runner/renv.lock
pipeline-runner/tests/testthat.R
pipeline-runner/tests/testthat/setup.R
pipeline-runner/tests/testthat/test-qc-7-embed_and_cluster.R

We are patching cellsets through the API, but currently don't have any tests for that functionality. The goal is to add them.
https://biomage.atlassian.net/browse/BIOMAGE-1759
N/A
https://github.com/hms-dbmi-cellenics/worker/pull/266
master

[BIOMAGE-1759] Test cellsets patching through the API.

---

codecov.yaml

enforce positive test coverage again

---

pipeline-runner/R/qc-7-embed_and_cluster.R

Explanation in api PR
N/A
N/A (in api)
https://github.com/hms-dbmi-cellenics/worker/pull/272
https://github.com/hms-dbmi-cellenics/api/pull/349
master

Fix patch cell sets

---

.github/workflows/ci.yaml
pipeline-runner/renv.lock

bump scdblfinder

---

.github/workflows/ci.yaml

https://biomage.atlassian.net/browse/BIOMAGE-1975
N/A
master

[BIOMAGE-1975] Pushing releases to new repo

---

.github/workflows/ci.yaml

Not pushing releases to IAC anymore 
https://biomage.atlassian.net/browse/BIOMAGE-1980
N/A
https://github.com/hms-dbmi-cellenics/ui/pull/753
https://github.com/hms-dbmi-cellenics/api/pull/383
https://github.com/hms-dbmi-cellenics/pipeline/pull/256
https://github.com/hms-dbmi-cellenics/worker/pull/282
master

[BIOMAGE-1980] Stop pushing releases to iac

---

.flux.yaml

Using https instead of ssh to avoid having to add tokens to flux in read-only mode.
https://biomage.atlassian.net/browse/BIOMAGE-1955
N/A
master

[BIOMAGE-1955] Changed .flux to use https for charts

---

.github/workflows/ci.yaml
.github/workflows/pr_validate.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2014
N/A
master

[BIOMAGE-2014] Using latest branch commit to tag docker images & validate PRs

---

.flux.yaml

https://biomage.atlassian.net/browse/BIOMAGE-1955
N/A
N/A
master

Fix chart path

---

pipeline-runner/DESCRIPTION

Forgot to push this to #257. This is necessary to not have conflicts when installing the development dependencies. The batchelor version in renv.lock is not the latest one, but when running renv::install() (only used for interactive development) to install the dependencies listed in the description file, the latest is installed, and renv conflicts.
N/A
https://ui-german-w285-pipeline263.scp-staging.biomage.net/
https://github.com/hms-dbmi-cellenics/worker/pull/285
master
Integration tests have to pass before the PR can be merged. Without …

fix batchelor version in description file

---

.github/workflows/ci.yaml

PR #261  introduces a fix to use the appropriate commit sha to tag images. It is tagging the docker images properly, but wasn't properly picked up by the staging-candidates for the PRs. This PR fixes that.
https://biomage.atlassian.net/browse/BIOMAGE-2014
N/A
N/A
master

[BIOMAGE-2014] - Fix staging SHA

---

pipeline-runner/R/gem2s-2-load_user_files.R
pipeline-runner/tests/testthat/test-gem2s-2-load_user_files.R

For multiome data, remove features that are not "Gene Expression" to match the count matrix rownames.
N/A
https://ui-sara-pipeline265.scp-staging.biomage.net/
master

[BIOMAGE-2035] filter non-gene-expression features

---

Makefile

Whenever the `sysdata.R` file is modified, it needs to be run again in order to regenerate the env file `sysdata.rda` where we actually import constants. I've added this step in the Makefile build/run to make it harder to forget about it.
N/A
N/A
master

updating sysdata.rda in every build

---

Makefile

Updating sysdata seems to break linux builds. I'm adding it to a different step but I suggest to get rid of the file for good.
N/A
N/A
master

not updating sysdata.R as part of the build step

---

.github/workflows/ci.yaml

Add updated default region

---

pipeline-runner/R/seurat-2-load_seurat.R

Signed-off-by: Alex Pickering <alexvpickering@gmail.com>
- ensures either `umap` or `tsne` is present in Seurat object (current reductions platform set up to support)
N/A
N/A
master

require umap or tsne

---

chart-infra/templates/datadog-sidecar-rbac.yaml
chart-infra/templates/pod-template.tpl

HMS deployment has no datadog
N/A
N/A
master

conditional datadog

---

pipeline-runner/R/seurat-3-upload_seurat_to_aws.R

`find_group_columns` wasn't working correctly because the column order was changed by the `group_by` operation. 
N/A
N/A
master

fix find seurat groups bug

---

local-runner/cf-local-container-launcher.yaml
local-runner/src/app.js

use default aws region locally

---

.githooks/commit-msg
Makefile

https://github.com/hms-dbmi-cellenics/issues/issues/6
N/A
https://github.com/hms-dbmi-cellenics/api/pull/460
https://github.com/hms-dbmi-cellenics/worker/pull/315
https://github.com/hms-dbmi-cellenics/ui/pull/849
https://github.com/hms-dbmi-cellenics/iac/pull/553
master

init automagic DCO sign offs and check

---

chart-infra/templates/scale-to-zero.yaml

EKS version 1.26 deprecates this. Already tested and working ok.
master

Deprecated batch/v1beta resource

---

.github/workflows/ci.yaml

Changing CI so it can run PRs opened from biomage by adding the "safe to run" label.
N/A
N/A
master

added is-safe-to-run check in CI

---

.github/workflows/ci.yaml

description in [worker PR](https://github.com/hms-dbmi-cellenics/worker/pull/326)
N/A
N/A
master

fix checkout

---

.github/workflows/ci.yaml

some omitted switches from `pull_request` to `pull_request_target`.
N/A
N/A
https://github.com/hms-dbmi-cellenics/worker/pull/327
master

fix event name checks

---

pipeline-runner/DESCRIPTION
pipeline-runner/Dockerfile
pipeline-runner/renv.lock
pipeline-runner/renv.lock.init
pipeline-runner/setup/restore_fast.R
pipeline-runner/setup/restore_renv.R

Building the docker image is slow for worker and pipeline. This uses `pkgbuild` to pre-restore as much as possible as quickly as possible.
N/A
N/A
master

implement fast restore

---

.github/workflows/ci.yaml

fixes docker buildcache so images dont need full rebuild on every commit.
https://github.com/hms-dbmi-cellenics/issues/issues/21
N/A
https://github.com/hms-dbmi-cellenics/worker/pull/329
master

fix buildcache

---

pipeline-runner/Dockerfile

switch to virtualenv

---

pipeline-runner/R/init-functions.R
pipeline-runner/R/qc-7-embed_and_cluster.R
pipeline-runner/tests/testthat/test-qc-7-embed_and_cluster.R

The path to the cell-level metadata table is passed by the API as part of the QC "input". It needs to be inside the step config so that it is available when needed.
N/A
N/A
https://github.com/hms-dbmi-cellenics/api/pull/504
master

fix: add cell-level metadata path to required config

---

pipeline-runner/R/qc-7-embed_and_cluster.R
pipeline-runner/tests/testthat/test-qc-7-embed_and_cluster.R

https://github.com/orgs/hms-dbmi-cellenics/projects/4/views/1?pane=issue&itemId=44736415
N/A
https://ui-martinfosco-pipeline15.scp-staging.biomage.net/
https://github.com/biomage-org/pipeline/pull/15
master

[Cell-level metadata] Fix cell level cellsets not getting created in some cases

---

pipeline-runner/R/gem2s-6-construct_qc_config.R
pipeline-runner/R/gem2s-6-prepare_experiment.R
pipeline-runner/R/seurat-3-upload_seurat_to_aws.R
pipeline-runner/tests/testthat/test-gem2s-6-construct_qc_config.R
pipeline-runner/tests/testthat/test-gem2s-6-prepare_experiment.R
pipeline-runner/tests/testthat/test-gem2s-7-upload_to_aws.R
pipeline-runner/tests/testthat/test-subset-1-subset_seurat.R

Improve support for parse data

---

pipeline-runner/R/handle_data.R
pipeline-runner/tests/testthat/test-gem2s-6-prepare_experiment.R

Fix broken subset

---

pipeline-runner/R/qc-7-embed_and_cluster.R

Leiden clustering breaks if qc filters are changed. This PR fixes the issue.
N/A
N/A
master

Fix Leidein clustering

---

pipeline-runner/R/qc-6-integrate_scdata-seuratv4.R
pipeline-runner/tests/testthat/test-qc-6-integrate_scdata-seuratv4.R

Cells were not filtered when running seuratv4 integration, this PR fixes it.
N/A
N/A
master

Filter out cells in SeuratV4 integration

---

.github/workflows/ci.yaml

fix test_local fallback

---

.flux.yaml

update flux api version

---

pipeline-runner/R/obj2s-3-upload_obj2s_to_aws.R
pipeline-runner/tests/testthat/test-obj2s-3-upload_obj2s_to_aws.R

uses input technology instead of hardcoding of `"seurat"`
N/A
N/A
master

use correct technology for qc_config for obj2s
